spring:
  datasource:
    url: jdbc:postgresql://postgres.db.svc/voffice
    username: voffice
    password: Vo2022!@#
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: info
    org.springframework.boot: info
    io.jaegertracing.internal.reporters.LoggingReporter: warn
