apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: config-service


build:
  artifacts:
    - image: localhost:8082/microservices/service/config-service
      context: .
      jib:
        type: gradle
        fromImage: localhost:8082/microservices/jdk/openjdk:21-ea-17-jdk-slim-buster
        args:
          - -Djib.allowInsecureRegistries=true
          - -Djib.to.auth.username=admin
          - -Djib.to.auth.password=admin

deploy:
  helm:
    releases:
      - name: config-service
        chartPath: _helm
        namespace: be
        setValueTemplates:
          image.repository: "{{ .IMAGE_REPO }}"
          image.tag: "{{ .IMAGE_TAG }}"
          fullnameOverride: config-service
