spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://voffice4-dev.viettel.vn/auth/oidc
          jws-algorithm: RS512
          jwk-set-uri: https://voffice4-dev.viettel.vn/auth/oidc/jwks
opentracing:
  jaeger:
    service-name: api-gateway-service.staging
logger:
  level:
    root: debug
    org.springframework: debug
    vn.viettel.voffice.gateway: debug